server:
  port: 8084

spring:
  application:
    name: recommendation-service
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/fourtune_db
    username: fourtune_user
    password: fourtune
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:redpanda:9092}
    consumer:
      group-id: recommendation-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-client-id
            client-secret: dummy-client-secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile, email
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: dummy-access-key
        secret-key: dummy-secret-key
      s3:
        bucket: dummy-bucket
        path-prefix: dummy-prefix
      stack:
        auto: false

feature:
  ai:
    provider: ${AI_PROVIDER:ollama} # ollama 또는 OpenAI

spring.ai:
  ollama:
    base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
    chat:
      model: llama3
  openai:
    api-key: ${OPENAI_API_KEY:}
    chat:
      model: gpt-3.5-turbo

app:
  oauth2:
    redirect-uri: http://localhost:3000/login-success

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000 # 1 hour
  refresh-token-expiration: 1209600000 # 14 days
